### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by 0BoUBoU0** [rovh/Noter#2]
Hello,

This addon is a great idea ! 
I have just one issue for now, when I try to enable the add-on in my classical blender (with a bunch of other addons), I get this error :

Traceback (most recent call last):
  File "C:\_OneForAll_\blender-2.83.5-windows64\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "F:\Dropbox\PrefsPersos\2.8x\scripts\addons\Noter-1-0-1\__init__.py", line 1281, in register
    nodeitems_utils.register_node_categories('CUSTOM_NODES', node_categories)
  File "C:\_OneForAll_\blender-2.83.5-windows64\2.83\scripts\modules\nodeitems_utils.py", line 105, in register_node_categories
    raise KeyError("Node categories list '%s' already registered" % identifier)
KeyError: "Node categories list 'CUSTOM_NODES' already registered"

Nevertheless, if i'm killing my preferences, and enable Noter, I get no error, and it's enabled perfectly. 
Cheers,

Yannick

**Comment by rovh** [comment]
I changed something in the master branch, give it a try. Please write if the script works.. https://github.com/rovh/Noter

**Comment by 0BoUBoU0** [comment]
It's now working perfectly well now ! thank you !

**Comment by rovh** [comment]
And thank you
